#!/usr/bin/env python3
"""The elementary Schur representation of Section 6.1 is the generalized q-Weyl
algebra with P(y) = 1 + y, so its twisted-trace space is one dimensional.

Standard library only. Prints a JSON record to standard output. Exact rational
arithmetic throughout: q is a rational parameter and states are finite Laurent
polynomials in zeta with rational coefficients on finitely many charge sectors.

Section 6.1 of the inverse-bulk manuscript 0.5 gives, on
H = l^2(Z) tensor L^2(S^1) with zeta = e^{i theta} and magnetic charge m,

    (v psi)_m(zeta)    = q^{-m} zeta psi_m(zeta),
    (u_- psi)_m(zeta)  = (1 + q^{-m-1} zeta) psi_{m+1}(q^{-1} zeta),
    (u_+ psi)_m(zeta)  = psi_{m-1}(q zeta).                                 (6.1)

Klyuev, *Twisted traces and positive forms on generalized q-Weyl algebras*,
SIGMA 18 (2022), 009, studies the algebra A(P) generated by U, V, Z, Z^{-1} with

    Z U Z^{-1} = q^2 U,   Z V Z^{-1} = q^{-2} V,   U V = P(q^{-1} Z),   V U = P(q Z),

for a Laurent polynomial P, and proves (Proposition 2.1) that the space of
g_t-twisted traces has dimension n, the number of nonzero roots of P counted
with multiplicity, and (Proposition 5.5) that T -> (T(1), ..., T(Z^{n-1})) is an
isomorphism onto C^n.

FIVE FACTS ARE CHECKED, on random exact states.

(1) u_+ u_- = 1 + q v.
(2) u_- u_+ = 1 + q^{-1} v.
(3) Z u_- Z^{-1} = q^2 u_- and Z u_+ Z^{-1} = q^{-2} u_+, with Z = v.
(4) Hence the assignment U = u_-, V = u_+, Z = v satisfies Klyuev's relations
    with P(y) = 1 + y:  U V = 1 + q^{-1} Z = P(q^{-1} Z) and
    V U = 1 + q Z = P(q Z).  The programme checks both as operator identities.
(5) P(y) = 1 + y has exactly one nonzero root, at y = -1, so n = 1 and by
    Proposition 2.1 the space of g_t-twisted traces is ONE DIMENSIONAL; by
    Proposition 5.5 a trace is fixed by the single value T(1). The root has
    |-1| = 1 and q < 1 < q^{-1} for 0 < q < 1, so in Theorem 4.7 it is counted
    by l = 1, r = 0. The programme checks the root data and the annulus
    membership for a range of q.

WHAT THIS DOES AND DOES NOT ESTABLISH. (1)-(4) are exact operator identities on
the stated domain of finite Laurent states, verified on random exact inputs; they
identify the representation's algebra, not its physical adjoints, which Section
6.1 inherits from the doubled representation. (5) records the consequence of two
quoted theorems of Klyuev; the theorems themselves are not reproved here. Nothing
about positivity of the Weil form, about the Bloch lift of Section 6.4, or about
what the chosen STATE can do follows from this: the arithmetic parameters of
Section 6 live in the dressing, not in the algebra.
"""
from fractions import Fraction
import json
import random

# A state is {m: {k: Fraction}} meaning sum_m sum_k c_{m,k} zeta^k on sector m.


def clean(state):
    out = {}
    for m, poly in state.items():
        trimmed = {k: c for k, c in poly.items() if c != 0}
        if trimmed:
            out[m] = trimmed
    return out


def scale_argument(poly, factor):
    """psi(factor * zeta) for a Laurent polynomial."""
    return {k: c*factor**k for k, c in poly.items()}


def act_v(state, q):
    return clean({m: {k + 1: c*q**(-m) for k, c in poly.items()}
                  for m, poly in state.items()})


def act_v_inverse(state, q):
    return clean({m: {k - 1: c*q**m for k, c in poly.items()}
                  for m, poly in state.items()})


def act_u_minus(state, q):
    out = {}
    for m in {mm - 1 for mm in state}:
        poly = state.get(m + 1)
        if poly is None:
            continue
        shifted = scale_argument(poly, 1/q)
        result = dict(shifted)
        for k, c in shifted.items():
            result[k + 1] = result.get(k + 1, Fraction(0)) + c*q**(-m - 1)
        out[m] = result
    return clean(out)


def act_u_plus(state, q):
    out = {}
    for m in {mm + 1 for mm in state}:
        poly = state.get(m - 1)
        if poly is None:
            continue
        out[m] = scale_argument(poly, q)
    return clean(out)


def combine(a, b, alpha=Fraction(1), beta=Fraction(1)):
    out = {}
    for m in set(a) | set(b):
        poly = {}
        for k, c in a.get(m, {}).items():
            poly[k] = poly.get(k, Fraction(0)) + alpha*c
        for k, c in b.get(m, {}).items():
            poly[k] = poly.get(k, Fraction(0)) + beta*c
        out[m] = poly
    return clean(out)


def equal(a, b):
    return clean(a) == clean(b)


def random_state(rng, sectors=3, degree=3):
    state = {}
    for m in range(-sectors, sectors + 1):
        poly = {}
        for k in range(-degree, degree + 1):
            if rng.random() < 0.6:
                poly[k] = Fraction(rng.randint(-6, 6), rng.randint(1, 5))
        if poly:
            state[m] = poly
    return clean(state) or {0: {0: Fraction(1)}}


def main():
    rng = random.Random(20260916)
    checks = {"u_plus_u_minus": 0, "u_minus_u_plus": 0, "grading": 0,
              "klyuev_relations": 0, "root_data": 0}
    parameters = [Fraction(1, 2), Fraction(1, 3), Fraction(2, 5), Fraction(3, 7)]
    samples = []

    for q in parameters:
        for _ in range(12):
            psi = random_state(rng)
            v_psi = act_v(psi, q)

            left = act_u_plus(act_u_minus(psi, q), q)
            right = combine(psi, v_psi, Fraction(1), q)
            assert equal(left, right), ("u_+ u_- = 1 + q v", q)
            checks["u_plus_u_minus"] += 1

            left = act_u_minus(act_u_plus(psi, q), q)
            right = combine(psi, v_psi, Fraction(1), 1/q)
            assert equal(left, right), ("u_- u_+ = 1 + q^{-1} v", q)
            checks["u_minus_u_plus"] += 1

            conj = act_v(act_u_minus(act_v_inverse(psi, q), q), q)
            target = {m: {k: c*q**2 for k, c in poly.items()}
                      for m, poly in act_u_minus(psi, q).items()}
            assert equal(conj, target), ("Z u_- Z^{-1} = q^2 u_-", q)
            conj = act_v(act_u_plus(act_v_inverse(psi, q), q), q)
            target = {m: {k: c/q**2 for k, c in poly.items()}
                      for m, poly in act_u_plus(psi, q).items()}
            assert equal(conj, target), ("Z u_+ Z^{-1} = q^{-2} u_+", q)
            checks["grading"] += 2

            # Klyuev's relations with U = u_-, V = u_+, Z = v, P(y) = 1 + y.
            uv = act_u_minus(act_u_plus(psi, q), q)
            assert equal(uv, combine(psi, act_v(psi, q), Fraction(1), 1/q)), \
                ("U V = P(q^{-1} Z)", q)
            vu = act_u_plus(act_u_minus(psi, q), q)
            assert equal(vu, combine(psi, act_v(psi, q), Fraction(1), q)), \
                ("V U = P(q Z)", q)
            checks["klyuev_relations"] += 2

        # P(y) = 1 + y: one nonzero root at -1, inside the annulus q < |a| < 1/q.
        root, modulus = Fraction(-1), Fraction(1)
        assert 1 + root == 0
        assert q < modulus < 1/q
        checks["root_data"] += 1
        samples.append({"q": str(q), "P": "1 + y", "n": 1,
                        "root": str(root), "abs_root": str(modulus),
                        "in_annulus_q_to_1_over_q": True,
                        "Theorem_4_7_l": 1, "Theorem_4_7_r": 0})

    print(json.dumps({
        "status": "passed",
        "date": "2026-09-16",
        "model": "claude-opus-5",
        "arithmetic": "exact rational; q rational, states finite Laurent "
                      "polynomials with rational coefficients",
        "checks": checks,
        "total_checks": sum(checks.values()),
        "identification": {
            "algebra": "generalized q-Weyl algebra A(P) of Klyuev, SIGMA 18 (2022) 009",
            "assignment": "U = u_-, V = u_+, Z = v",
            "P": "1 + y",
            "n_nonzero_roots": 1,
            "twisted_trace_dimension": 1,
            "determined_by": "the single value T(1), by Proposition 5.5",
        },
        "parameters": samples,
        "reading": "The elementary representation used for the prime references "
                   "is the generalized q-Weyl algebra with P(y) = 1 + y. Its "
                   "space of twisted traces is one dimensional, so the algebra's "
                   "own invariant pairing carries no arithmetic parameter at all. "
                   "Every prime parameter in Section 6 enters through the chosen "
                   "dressing state, which Section 6.5 shows is unconstrained. The "
                   "twisted-trace classification therefore bounds what one copy "
                   "of the algebra can do and says nothing about the Bloch lift, "
                   "which uses infinitely many orthogonal copies.",
        "scope": "An identification of the algebra and its consequence under two "
                 "quoted theorems. No positivity statement, no claim about the "
                 "physical adjoints, and no reproof of the quoted theorems.",
    }, indent=2))


if __name__ == "__main__":
    main()
