#!/usr/bin/env python3
"""Exact real jets of a bounded holomorphic remainder and paid current geometry.

The analytic Schwarz lemma is proved in Heat Note 18. This program checks
the rational extremizers, support formulas, Schur coefficients and one
application to an already certified complete genuine rectangle. It does
not certify a sector-wide arithmetic current sign.
"""
from fractions import Fraction as F
import hashlib
import itertools
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CERTIFICATE = ROOT / 'newman_collisions/13_microlocal_phase_space/numerics/COMPLETE_CURRENT_RECTANGLE_CERTIFICATE_20261010.json'
EXPECTED_CERTIFICATE_SHA256 = '980031983c6c05b70f6bbd101dad13a2a4354dfc4c4a6b735909ddc93df423e2'
checks = 0


def check(value):
    global checks
    assert value, checks + 1
    checks += 1


def sign(x):
    return (x > 0) - (x < 0)


def dot(a, b):
    return sum((x*y for x, y in zip(a, b)), F(0))


def support(A, B):
    """Support of C={(a,b):a*a+abs(b)<=1}, with an attaining point."""
    A, B = F(A), F(B)
    if B and abs(A) <= 2*abs(B):
        a = A/(2*abs(B))
        b = sign(B)*(1-a*a)
    else:
        a, b = F(sign(A)), F(0)
    return A*a+B*b, (a, b)


def upper_decimal(x, places=12):
    scale = 10**places
    top = -((-x.numerator*scale)//x.denominator)
    whole, tail = divmod(top, scale)
    return f'{whole}.{tail:0{places}d}'


def lower_decimal(x, places=12):
    scale = 10**places
    bottom = (x.numerator*scale)//x.denominator
    whole, tail = divmod(bottom, scale)
    return f'{whole}.{tail:0{places}d}'


def run():
    fractions = [F(n, 8) for n in range(-8, 9)]
    directions = (F(-3), F(-1), F(-1, 2), F(0), F(1, 2), F(1), F(3))
    for A, B in itertools.product(directions, repeat=2):
        h, z = support(A, B)
        check(z[0]**2+abs(z[1]) <= 1)
        check(dot((A, B), z) == h)
        check(h >= 0)
        check(h <= abs(A)+abs(B))
        for a, lam in itertools.product(fractions, repeat=2):
            b = (1-a*a)*lam
            check(a*a+abs(b) <= 1)
            check(A*a+B*b <= h)
            # Exact disk automorphism identity for complex rational zeta.
            for x, y in ((F(0), F(0)), (F(1, 3), F(1, 4))):
                denominator2 = (1+a*lam*x)**2+(a*lam*y)**2
                numerator2 = (a+lam*x)**2+(lam*y)**2
                check(denominator2-numerator2 == (1-a*a)*(1-lam*lam*(x*x+y*y)))
                check(denominator2 > 0)
                check(denominator2-numerator2 >= 0)

        if A == B == 0:
            continue
        norm2 = A*A+B*B
        for eta, j in itertools.product((F(0), F(1, 7), F(2)), (F(-5), F(0), F(1, 9), F(7))):
            excess = max(2*abs(j)-eta*h, F(0))
            if excess:
                error = tuple(sign(j)*eta*v for v in z)
                q = (sign(j)*excess*A/norm2, sign(j)*excess*B/norm2)
                observed = tuple((e+r)/2 for e, r in zip(error, q))
            else:
                check(h > 0)
                error = tuple(2*j*v/h for v in z)
                q = (F(0), F(0))
                observed = tuple(e/2 for e in error)
            check(dot((A, B), observed) == j)
            if eta:
                check((error[0]/eta)**2+abs(error[1]/eta) <= 1)
            else:
                check(error == (0, 0))
            check(dot(q, q)*norm2 == excess*excess)
            # Independent feasible Schur jets and tangent displacements.
            for a, lam, tangent in itertools.product((F(-1), F(-1, 3), F(0), F(1)), (F(-1), F(0), F(1)), (F(-2), F(0), F(3, 5))):
                alternative = (observed[0]+tangent*B, observed[1]-tangent*A)
                truepair = (2*alternative[0]-eta*a, 2*alternative[1]-eta*(1-a*a)*lam)
                check(dot(truepair, truepair)*norm2 >= excess*excess)

    # Norm corollaries use the manuscript's two distinct derivative scales.
    for a, lam in itertools.product(fractions, repeat=2):
        b = (1-a*a)*lam
        check(a*a+b*b <= 1)
        check(a*a/4+4*b*b <= 4)

    # Real coefficients through zeta^2 are generated by two Schur steps.
    for a, lam, nu in itertools.product(fractions, repeat=3):
        D = 1-a*a
        b = D*lam
        c = D*((1-lam*lam)*nu-a*lam*lam)
        if D:
            check(b/D == lam)
            check(c/D+a*b*b/(D*D) == (1-lam*lam)*nu)
            check(abs(c+a*b*b/D) <= D-b*b/D)
            for x in (F(-1, 2), F(0), F(1, 2)):
                inner = (lam+nu*x)/(1+lam*nu*x)
                g = (a+x*inner)/(1+a*x*inner)
                check(abs(g) <= 1)
        else:
            check(b == c == 0)

    # The analytic error body excludes points admitted by the old square.
    check(F(3, 4)**2+abs(F(3, 4)) > 1)
    check(abs(F(3, 4)) <= 1)
    # Sharp current tolerance falls by 3/8 for equal coefficient moduli.
    check(support(1, 1)[0] == F(5, 4))
    check(support(1, 1)[0]/2 == F(5, 8))

    data = CERTIFICATE.read_bytes()
    check(hashlib.sha256(data).hexdigest() == EXPECTED_CERTIFICATE_SHA256)
    rectangle = json.loads(data)['rectangle']
    loL, hiL = map(F, rectangle['L'])
    lov, hiv = map(F, rectangle['complete_S_enclosure']['imaginary'])
    dv = max(abs(F(v)) for v in rectangle['complete_Sprime_enclosure']['imaginary'])
    eta = F(rectangle['eta_upper_enclosure'][1])
    lowerJ = F(rectangle['complete_current_enclosure'][0])
    check(lov > 0)
    check(dv <= 2*loL*lov)
    tolerance = eta*(hiL*hiv+dv*dv/(4*loL*lov))/2
    gap = lowerJ-tolerance
    denominator2 = (hiL*hiv)**2+dv*dv
    check(tolerance < F(136, 1000))
    check(gap > F(5107, 1000))
    check(4*gap*gap > F(36, 100)**2*denominator2)
    return {
        'status': 'PASS',
        'source_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        'assertions_passed': checks,
        'families': [
            'exact parabolic error-body support and attaining Schur jets',
            'bounded real disk-map identity including constant endpoint maps',
            'sharp current-line distance and compatible abstract extremizers',
            'second Taylor coefficient correlation from two Schur steps',
            'strict improvement over independent rectangular payments',
            'hash-bound complete genuine rectangle with rational sign checks',
        ],
        'prior_rectangle': {
            'certificate_sha256': EXPECTED_CERTIFICATE_SHA256,
            'new_current_tolerance_upper': upper_decimal(tolerance),
            'new_current_gap_lower': lower_decimal(gap),
            'natural_joint_vector_norm_lower': '0.36',
            'method': 'exact rational endpoints; norm lower bound checked by squaring positive quantities',
        },
        'scope': 'General analytic error geometry and its conditional application to the retained finite complete rectangle; no sector-wide arithmetic margin or RH assertion.',
    }


if __name__ == '__main__':
    print(json.dumps(run(), indent=2, sort_keys=True))
